openapi: 3.1.0
info:
  version: '0.1.0'
  title: 'Public Chrood API'
  license:
    name: Apache2.0
paths:
  /user:
    post:
      description: 'Creates a new user'
      operationId: "createUser"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email_address:
                  description: "The primary email address of the user used for authentication."
                  type: string
                password:
                  description: "The password to authenticate the user."
                  type: string
              required:
                - email_address
                - password
      responses:
        "200":
          description: "User was successfully created"
          content:
            application/json:
              schema:
                type: object
                properties:
                  email_address:
                    description: "The primary email address of the user."
                    type: string
        default:
          description: "The user could not be created due to an unexpected error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    description: "A descriptive text of the error indicating why the request failed."
                    type: string
security:
  - BasicAuth: []